site_name: DIPS Process and Functionality 
nav:
- Introduction: index.md
- Functional Documentation:   
    - 'Arena 18.1' :     
        - 'Norwegian' : norwegianDocs.md   
        - 'English' : englishDocs.md  
        
    - 'Arena 19.1' : 
        - 'Norwegian' : norwegianDocs.md   
        - 'English' : englishDocs.md          
        - 'Package Manager': Package_Manager.md
      
- Technical Documentation:
    - 'Arena 18.1' : 
        - 'Technical' : 18_1_TechnicalDocuments.md        

    - 'Arena 19.1' : 
       - 'Technical' : 18_1_TechnicalDocuments.md
    
theme:
  name: 'material'
  
markdown_extensions:
- admonition
- codehilite

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

  